version: '3'
networks:
   profile-network:
       external: true
       name: 'mongo-network'

services:
  app:
    container_name: profileapp
    image: profileapp:1.0
    build: .   # Location of Dockerfile
    ports:
      - 3000:3000
    environment:
      - MONGO_PASS=secret
      - MONGO_HOST=database  # 修改这里
    networks:
       - profile-network
    depends_on:
      - database

  database:
    container_name: mongoDB
    image: mongo:8.0-rc
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
       - profile-network
    volumes:
      - profiledata:/db/data  # 使用命名卷进行持久化

  mongo-express:
    container_name: express
    image: mongo-express:1.0-20-alpine3.19
    restart: always # fixes MongoNetworkError caused by mongodb not being ready when mongo-express starts.
    ports:
      - 8080:8080  # 将容器的 8080 映射到主机的 8080
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_SERVER=database  # 修改这里
    networks:
       - profile-network
    depends_on:
      - database

volumes:
  profiledata:  # 使用命名卷来持久化数据库数据
